using Microsoft.CodeAnalysis;
using RazorStatic.SourceGen.Utilities;
using System.Collections.Immutable;
using System.IO;

namespace RazorStatic.SourceGen.Pipelines;

internal static partial class GeneratorPipelines
{
    public static void ExecuteDirectoriesSetupPipeline(
        SourceProductionContext context,
        (CsProjProperties, ImmutableArray<AttributeMembers>) source)
    {
        var (csProj, attributes) = source;

        if (string.IsNullOrWhiteSpace(csProj.ProjectDir)
            || attributes.IsDefaultOrEmpty
            || attributes[0].MemberData.IsDefaultOrEmpty)
            return;

        var properties = attributes[0].MemberData[0].Properties;
        var pagesDir = properties.TryGetValue(
            Constants.Attributes.DirectoriesSetup.Members.Pages,
            out var pagesDirName)
            ? Path.Combine(csProj.ProjectDir, pagesDirName)
            : string.Empty;

        var contentDir = properties.TryGetValue(
            Constants.Attributes.DirectoriesSetup.Members.Content,
            out var contentDirName)
            ? Path.Combine(csProj.ProjectDir, contentDirName)
            : string.Empty;

        const string className = $"Implementations_{Constants.Interfaces.DirectoriesSetup.Name}";

        context.AddSource(
            $"{className}.generated.cs",
            $$"""
              // <auto-generated/>
              using {{Constants.RazorStaticAbstractionsNamespace}};

              namespace {{Constants.RazorStaticGeneratedNamespace}}
              {
                  internal sealed class {{className}} : {{Constants.Interfaces.DirectoriesSetup.Name}}
                  {
              #nullable disable
                      public string {{Constants.Interfaces.DirectoriesSetup.Members.ProjectRoot}} => @"{{csProj.ProjectDir}}";
                      
                      public string {{Constants.Interfaces.DirectoriesSetup.Members.Pages}} => @"{{pagesDir}}";
                      
                      public string {{Constants.Interfaces.DirectoriesSetup.Members.Content}} => @"{{contentDir}}";
              #nullable enable
                  }
              }
              """);
    }
}