using Microsoft.CodeAnalysis;
using RazorStatic.SourceGen.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Capture = RazorStatic.SourceGen.Utilities.Capture;

namespace RazorStatic.SourceGen.Pipelines;

internal static partial class GeneratorPipelines
{
    public static void ExecutePageCollectionsPipeline(SourceProductionContext context, Capture capture)
    {
        if (string.IsNullOrWhiteSpace(capture.Properties.ProjectDir)
            || string.IsNullOrWhiteSpace(capture.AssemblyName)
            || capture.AttributeMembers.IsDefaultOrEmpty)
            return;

        var pagesForFactory  = new Dictionary<string, string>();
        var keysForDirectory = new Dictionary<string, string>();
        var pagesDirName     = capture.DirectorySetup.Properties[Constants.Attributes.DirectoriesSetup.Members.Pages];
        var contentDirName   = capture.DirectorySetup.Properties[Constants.Attributes.DirectoriesSetup.Members.Content];

        const string key              = Constants.Attributes.CollectionDefinition.Members.Key;
        const string pageRoute        = Constants.Attributes.CollectionDefinition.Members.PageRoute;
        const string contentDirectory = Constants.Attributes.CollectionDefinition.Members.ContentDirectory;
        const string extension        = Constants.Attributes.CollectionDefinition.Members.Extension;

        foreach (var attributeInfo in capture.AttributeMembers.Where(
                     info => info.Properties.ContainsKey(key)
                             && info.Properties.ContainsKey(pageRoute)
                             && info.Properties.ContainsKey(contentDirectory)
                             && info.Properties.ContainsKey(extension)))
        {
            try
            {
                var routeName = attributeInfo.Properties[pageRoute];
                var routeDir  = Path.Combine(capture.Properties.ProjectDir, pagesDirName, routeName);
                var pageFile = Directory.GetFiles(routeDir, "*.razor", SearchOption.AllDirectories)
                                        .FirstOrDefault(
                                            file =>
                                            {
                                                var split             = file.Split(Path.DirectorySeparatorChar);
                                                var fileWithExtension = split[split.Length - 1];
                                                return fileWithExtension.StartsWith("[")
                                                       && fileWithExtension.EndsWith("].razor");
                                            });

                if (string.IsNullOrWhiteSpace(pageFile))
                    continue;

                var collectionDir = Path.Combine(
                    capture.Properties.ProjectDir,
                    contentDirName,
                    attributeInfo.Properties[contentDirectory]);
                var collectionRootDir = collectionDir.Substring(
                    0,
                    collectionDir.LastIndexOf(Path.DirectorySeparatorChar));
                var contentFiles = Directory.GetFiles(
                                                collectionDir,
                                                attributeInfo.Properties[extension],
                                                SearchOption.AllDirectories)
                                            .Select(file => $"@\"{file}\"");

                var routeNameNoSpecialChars = new Regex("[^a-zA-Z0-9]").Replace(routeName, "");
                var className =
                    $"Implementations_{Constants.Interfaces.PageCollectionDefinition.Name.Replace("Page", routeNameNoSpecialChars)}";

                context.AddSource(
                    $"{className}.generated.cs",
                    $$"""
                      // <auto-generated/>
                      using Microsoft.AspNetCore.Components;
                      using Microsoft.AspNetCore.Components.Web;
                      using {{Constants.RazorStaticAbstractionsNamespace}};
                      using {{Constants.RazorStaticComponentsNamespace}};
                      using {{Constants.RazorStaticUtilitiesNamespace}};
                      using System;
                      using System.Collections.Frozen;
                      using System.Collections.Generic;
                      using System.IO;
                      using System.Threading.Tasks;

                      namespace {{Constants.RazorStaticCoreNamespace}}
                      {
                          internal sealed class {{className}} : {{Constants.Interfaces.PageCollectionDefinition.Name}}
                          {
                              private const string YamlIndicator = "---\r\n";
                              
                      #nullable enable
                              private static readonly FrozenSet<string> ContentFilePaths = new HashSet<string>()
                              {
                                  {{string.Join(",\n            ", contentFiles)}}
                              }
                              .ToFrozenSet();
                              
                              private readonly HtmlRenderer _renderer;
                              
                              public string {{Constants.Interfaces.PageCollectionDefinition.Members.RootPath}} => @"{{collectionRootDir}}";
                              
                              public {{className}}(HtmlRenderer renderer) => _renderer = renderer;
                      
                              public async IAsyncEnumerable<RenderedResult> {{Constants.Interfaces.PageCollectionDefinition.Members.RenderComponentsAsync}}(string filePath, Type pageType)
                              {
                                  foreach (var contentFilePath in ContentFilePaths)
                                  {
                                      var content = await _renderer.Dispatcher.InvokeAsync(async () =>
                                      {
                                          var text = File.ReadAllText(contentFilePath)?.Trim();
                                          if (string.IsNullOrWhiteSpace(text))
                                              return string.Empty;
                                          
                                          string? frontmatterContent = null;
                                          string? fileContent = null;
                                          if (text.StartsWith(YamlIndicator))
                                          {
                                              var yamlEndIndex = text.IndexOf(YamlIndicator, YamlIndicator.Length, StringComparison.InvariantCulture);
                                              if (yamlEndIndex > YamlIndicator.Length)
                                              {
                                                  frontmatterContent = text[YamlIndicator.Length..yamlEndIndex].Trim();
                                                  fileContent = text[(yamlEndIndex + YamlIndicator.Length)..].Trim();
                                              }
                                          }
                                          else
                                          {
                                              fileContent = text;
                                          }
                                          
                                          var parameters = ParameterView.FromDictionary(new Dictionary<string, object?>
                                          {
                                              [nameof({{Constants.Abstractions.FileComponentBase.Name}}.{{Constants.Abstractions.FileComponentBase.Members.PageFilePath}})] = filePath,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.ContentFilePath}})] = contentFilePath,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.Slug}})] = SlugUtils.Convert(Path.GetFileNameWithoutExtension(contentFilePath).ToLowerInvariant()),
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.FrontMatter}})] = frontmatterContent,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.Content}})] = fileContent
                                          });
                                          var output = await _renderer.RenderComponentAsync(pageType, parameters);
                                          return output.ToHtmlString();
                                      });
                                      yield return new RenderedResult(contentFilePath, content);
                                  }
                              }
                      #nullable disable
                          }
                      }
                      """);

                pagesForFactory[pageFile]                       = className;
                keysForDirectory[attributeInfo.Properties[key]] = collectionDir;
            }
            catch (Exception)
            {
                // ignored
            }
        }

        context.AddSource(
            "Implementations_PageCollectionsStore.generated.cs",
            $$"""
              // <auto-generated/>
              using Microsoft.AspNetCore.Components.Web;
              using {{Constants.RazorStaticAbstractionsNamespace}};
              using System.Collections.Frozen;
              using System.Collections.Generic;
              using System.Diagnostics.CodeAnalysis;
              using System.IO;

              namespace {{Constants.RazorStaticCoreNamespace}}
              {
                  internal sealed class Implementations_PageCollectionsStore : {{Constants.Interfaces.PageCollectionsStore.Name}}
                  {
              #nullable enable
                      private readonly HtmlRenderer _renderer;
                      private readonly FrozenDictionary<string, {{Constants.Interfaces.PageCollectionDefinition.Name}}> _collections;
                      private readonly FrozenDictionary<string, string> _directories;
                      
                      public Implementations_PageCollectionsStore(HtmlRenderer renderer)
                      {
                          _renderer    = renderer;
                          _collections = new Dictionary<string, {{Constants.Interfaces.PageCollectionDefinition.Name}}>
                          {
                              {{string.Join(",\n            ", pagesForFactory.Select(kvp => $"[@\"{kvp.Key}\"] = new {kvp.Value}(renderer)"))}}
                          }
                          .ToFrozenDictionary();
                          _directories = new Dictionary<string, string>
                          {
                              {{string.Join(",\n            ", keysForDirectory.Select(kvp => $"[@\"{kvp.Key}\"] = @\"{kvp.Value}\""))}}
                          }
                          .ToFrozenDictionary();
                      }
                      
                      public bool {{Constants.Interfaces.PageCollectionsStore.Members.TryGetCollection}}(string filePath, [MaybeNullWhen(false)] out {{Constants.Interfaces.PageCollectionDefinition.Name}} collection)
                      {
                          return _collections.TryGetValue(filePath, out collection);
                      }
                      
                      public string[] {{Constants.Interfaces.PageCollectionsStore.Members.GetContentFileDirectories}}(string key)
                      {
                          if (!_directories.TryGetValue(key, out var collectionDirectory))
                          {
                              return [];
                          }
                          
                          return Directory.GetFiles(collectionDirectory, "*.md", SearchOption.AllDirectories) ?? [];
                      }
              #nullable disable
                  }
              }
              """);
    }
}