using Microsoft.CodeAnalysis;
using RazorStatic.SourceGen.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Capture = RazorStatic.SourceGen.Utilities.Capture;

namespace RazorStatic.SourceGen.Pipelines;

internal static partial class GeneratorPipelines
{
    public static void ExecutePageCollectionsPipeline(SourceProductionContext context, Capture capture)
    {
        if (string.IsNullOrWhiteSpace(capture.Properties.ProjectDir)
            || string.IsNullOrWhiteSpace(capture.AssemblyName)
            || capture.AttributeMembers.IsDefaultOrEmpty)
            return;

        var pagesForFactory = new Dictionary<string, string>();
        var pagesDirName    = capture.DirectorySetup.Properties[Constants.Attributes.DirectoriesSetup.Members.Pages];
        var contentDirName  = capture.DirectorySetup.Properties[Constants.Attributes.DirectoriesSetup.Members.Content];

        const string pageRoute        = Constants.Attributes.CollectionDefinition.Members.PageRoute;
        const string contentDirectory = Constants.Attributes.CollectionDefinition.Members.ContentDirectory;

        foreach (var attributeInfo in capture.AttributeMembers.Where(
                     info => info.Properties.ContainsKey(pageRoute)
                             && info.Properties.ContainsKey(contentDirectory)))
        {
            try
            {
                var routeName = attributeInfo.Properties[pageRoute];
                var routeDir  = Path.Combine(capture.Properties.ProjectDir, pagesDirName, routeName);
                var pageFile = Directory.GetFiles(routeDir, "*.razor", SearchOption.AllDirectories)
                                        .FirstOrDefault(
                                            file =>
                                            {
                                                var split             = file.Split(Path.DirectorySeparatorChar);
                                                var fileWithExtension = split[split.Length - 1];
                                                return fileWithExtension.StartsWith("[")
                                                       && fileWithExtension.EndsWith("].razor");
                                            });

                if (string.IsNullOrWhiteSpace(pageFile))
                    continue;

                var collectionDir = Path.Combine(
                    capture.Properties.ProjectDir,
                    contentDirName,
                    attributeInfo.Properties[contentDirectory]);
                var collectionRootDir = collectionDir.Substring(
                    0,
                    collectionDir.LastIndexOf(Path.DirectorySeparatorChar));
                var markdownFiles = Directory.GetFiles(collectionDir, "*.md", SearchOption.AllDirectories)
                                             .Select(file => $"@\"{file}\"");

                var routeNameNoSpecialChars = new Regex("[^a-zA-Z0-9]").Replace(routeName, "");
                var className =
                    $"Implementations_{Constants.Interfaces.PageCollectionDefinition.Name.Replace("Page", routeNameNoSpecialChars)}";

                context.AddSource(
                    $"{className}.generated.cs",
                    $$"""
                      // <auto-generated/>
                      using Microsoft.AspNetCore.Components;
                      using Microsoft.AspNetCore.Components.Web;
                      using {{Constants.RazorStaticAbstractionsNamespace}};
                      using {{Constants.RazorStaticComponentsNamespace}};
                      using System;
                      using System.Collections.Frozen;
                      using System.Collections.Generic;
                      using System.IO;
                      using System.Threading.Tasks;

                      namespace {{Constants.RazorStaticCoreNamespace}}
                      {
                          internal sealed class {{className}} : {{Constants.Interfaces.PageCollectionDefinition.Name}}
                          {
                              private const string YamlIndicator = "---\r\n";
                              
                      #nullable enable
                              private static readonly FrozenSet<string> ContentFilePaths = new HashSet<string>()
                              {
                                  {{string.Join(",\n            ", markdownFiles)}}
                              }
                              .ToFrozenSet();
                              
                              private readonly HtmlRenderer _renderer;
                              
                              public string {{Constants.Interfaces.PageCollectionDefinition.Members.RootPath}} => @"{{collectionRootDir}}";
                              
                              public {{className}}(HtmlRenderer renderer) => _renderer = renderer;
                      
                              public async IAsyncEnumerable<RenderedResult> {{Constants.Interfaces.PageCollectionDefinition.Members.RenderComponentsAsync}}(string filePath, Type pageType)
                              {
                                  foreach (var contentFilePath in ContentFilePaths)
                                  {
                                      var content = await _renderer.Dispatcher.InvokeAsync(async () =>
                                      {
                                          var text = File.ReadAllText(contentFilePath)?.Trim();
                                          string? frontmatterContent = null;
                                          string? markdownContent = null;
                                          if (text.StartsWith(YamlIndicator))
                                          {
                                              var yamlEndIndex = text.IndexOf(YamlIndicator, YamlIndicator.Length, StringComparison.InvariantCulture);
                                              if (yamlEndIndex > YamlIndicator.Length)
                                              {
                                                  frontmatterContent = text[YamlIndicator.Length..yamlEndIndex].Trim();
                                                  markdownContent = text[(yamlEndIndex + YamlIndicator.Length)..].Trim();
                                              }
                                          }
                                          else
                                          {
                                              markdownContent = text;
                                          }
                                          
                                          var parameters = ParameterView.FromDictionary(new Dictionary<string, object?>
                                          {
                                              [nameof({{Constants.Abstractions.FileComponentBase.Name}}.{{Constants.Abstractions.FileComponentBase.Members.PageFilePath}})] = filePath,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.ContentFilePath}})] = contentFilePath,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.Content}})] = markdownContent,
                                              [nameof({{Constants.Abstractions.CollectionFileComponentBase.Name}}.{{Constants.Abstractions.CollectionFileComponentBase.Members.FrontMatter}})] = frontmatterContent
                                          });
                                          var output = await _renderer.RenderComponentAsync(pageType, parameters);
                                          return output.ToHtmlString();
                                      });
                                      yield return new RenderedResult(contentFilePath, content);
                                  }
                              }
                      #nullable disable
                          }
                      }
                      """);

                pagesForFactory[pageFile] = className;
            }
            catch (Exception)
            {
                // ignored
            }
        }

        context.AddSource(
            "Implementations_PageCollectionsStore.generated.cs",
            $$"""
              // <auto-generated/>
              using Microsoft.AspNetCore.Components.Web;
              using {{Constants.RazorStaticAbstractionsNamespace}};
              using System.Collections.Frozen;
              using System.Collections.Generic;
              using System.Diagnostics.CodeAnalysis;

              namespace {{Constants.RazorStaticCoreNamespace}}
              {
                  internal sealed class Implementations_PageCollectionsStore : {{Constants.Interfaces.PageCollectionsStore.Name}}
                  {
              #nullable enable
                      private readonly HtmlRenderer _renderer;
                      private readonly FrozenDictionary<string, {{Constants.Interfaces.PageCollectionDefinition.Name}}> _collections;
                      
                      public Implementations_PageCollectionsStore(HtmlRenderer renderer)
                      {
                          _renderer    = renderer;
                          _collections = new Dictionary<string, {{Constants.Interfaces.PageCollectionDefinition.Name}}>
                          {
                              {{string.Join(",\n            ", pagesForFactory.Select(kvp => $"[@\"{kvp.Key}\"] = new {kvp.Value}(renderer)"))}}
                          }
                          .ToFrozenDictionary();
                      }
                      
                      public bool {{Constants.Interfaces.PageCollectionsStore.Members.TryGetCollection}}(string key, [MaybeNullWhen(false)] out {{Constants.Interfaces.PageCollectionDefinition.Name}} collection)
                      {
                          return _collections.TryGetValue(key, out collection);
                      }
              #nullable disable
                  }
              }
              """);
    }
}